name: kitchen

on:
  push:
    branches: [master, ci]
  pull_request:
    branches: [master]

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - amazonlinux-2
          - centos-8
          - debian-11
          - fedora-34
          - oraclelinux-8
          - ubuntu-2004
          - ubuntu-2204
        chef_version:
          - '15.3'
          - '16'
          - '17'
        suite: [default]
      fail-fast: false
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install Chef
      uses: actionshub/chef-install@main
    - name: Cookstyle
      run: cookstyle --display-cop-names --extra-details
    - name: Rspec
      run: chef exec rspec
    - name: Test Kitchen
      uses: actionshub/test-kitchen@main
      with:
        suite: ${{ matrix.suite }}
        os: ${{ matrix.os }}
      env:
        CHEF_LICENSE: accept-no-persist
        CHEF_VERSION: ${{ matrix.chef_version }}
        KITCHEN_LOCAL_YAML: kitchen.dokken.yml
